"""Fail-fast bridge between the lifecycle model and Cloudy C25.

The bridge generates explicit, deterministic photoionization inputs, requests
integrated emergent diagnostic-line fluxes, and normalizes them per incident
hydrogen-ionizing photon. It never silently falls back to the analytic
screening surrogate.
"""
from __future__ import annotations

import os
import re
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CLOUDY_EXE = PROJECT_ROOT / "work" / "cloudy" / "source" / "cloudy.exe"
C_LIGHT = 2.99792458e10

SED_COMMANDS = {
    "table_agn": "table agn",
    "agn_standard": "AGN 6.00 -1.40 -0.50 -1.0",
    # A deliberately X-ray-weak hypothesis motivated by the LRD marks.
    "agn_xray_weak": "AGN 6.00 -2.00 -0.50 -1.2",
    # Soft stellar-like continua provide a controlled test of the weak He II
    # lines in the public LRD grating spectra.  They are not asserted to be
    # literal single-temperature stellar populations.
    "blackbody_50000": "blackbody 50000 K",
    "blackbody_70000": "blackbody 70000 K",
    "blackbody_100000": "blackbody 100000 K",
    # This shape is generated by run_cloudy_filtered_agn_anchors.py and copied
    # into each model directory before execution.
    "agn_heplus_filtered": 'table read "filtered_agn.trn"',
}

# Stable machine keys and exact C25 line identifiers.
DIAGNOSTIC_LINES = (
    ("halpha", "H  1", "6562.80A", "air"),
    ("hbeta", "H  1", "4861.32A", "air"),
    ("hgamma", "H  1", "4340.46A", "air"),
    ("oii3726", "O  2", "3726.03A", "air"),
    ("oii3729", "O  2", "3728.81A", "air"),
    ("neiii3869", "Ne 3", "3868.76A", "air"),
    ("oiii4363", "O  3", "4363.21A", "air"),
    ("oiii5007", "O  3", "5006.84A", "air"),
    ("oi6300", "O  1", "6300.30A", "air"),
    ("nii6583", "N  2", "6583.45A", "air"),
    ("sii6716", "S  2", "6716.44A", "air"),
    ("sii6731", "S  2", "6730.82A", "air"),
    ("hei5876", "Blnd", "5875.66A", "air"),
    ("hei7065", "Blnd", "7065.25A", "air"),
    ("heii1640", "He 2", "1640.41A", "vacuum"),
    ("heii4686", "He 2", "4685.68A", "air"),
    ("paalpha", "H  1", "1.87510m", ""),
)


@dataclass(frozen=True)
class CloudyParameters:
    """One physical gas model in the LRD Cloudy grid."""

    logn: float
    logu: float
    lognh: float
    metallicity: float = 0.2
    dust_to_metals: float = 0.0
    sed: str = "agn_standard"
    geometry: str = "open"
    radius_log_cm: float = 17.0
    temperature: float | None = None
    microturbulence_kms: float = 0.0
    no_molecules: bool = False
    iterations: int | None = None

    def validate(self):
        if not (0.0 <= self.logn <= 16.0):
            raise ValueError("logn must be in [0, 16]")
        if not (-8.0 <= self.logu <= 4.0):
            raise ValueError("logu must be in [-8, 4]")
        if not (17.0 <= self.lognh <= 27.0):
            raise ValueError("lognh must be in [17, 27]")
        if not (0.001 <= self.metallicity <= 10.0):
            raise ValueError("metallicity must be in [0.001, 10] Z_sun")
        if not (0.0 <= self.dust_to_metals <= 3.0):
            raise ValueError("dust_to_metals must be in [0, 3]")
        if self.sed not in SED_COMMANDS:
            raise ValueError(f"unsupported SED {self.sed!r}")
        if self.geometry not in {"open", "sphere"}:
            raise ValueError("geometry must be 'open' or 'sphere'")
        if self.geometry == "sphere" and not (10.0 <= self.radius_log_cm <= 24.0):
            raise ValueError("spherical models need radius_log_cm in [10, 24]")
        if self.temperature is not None and self.temperature <= 0:
            raise ValueError("temperature must be positive")
        if self.microturbulence_kms < 0:
            raise ValueError("microturbulence_kms cannot be negative")
        if self.iterations is not None and not (1 <= self.iterations <= 20):
            raise ValueError("iterations must be in [1, 20] or None")

    @property
    def photon_flux(self):
        """Incident H-ionizing photon flux Phi(H) in photons cm^-2 s^-1."""
        return 10.0 ** (self.logn + self.logu) * C_LIGHT

    @property
    def ionizing_photon_rate(self):
        """Q(H) implied by U, n_H, and radius for a spherical model."""
        radius = 10.0**self.radius_log_cm
        return 4.0 * 3.141592653589793 * radius**2 * self.photon_flux


def write_line_list(path):
    """Write the exact diagnostic line identifiers understood by C25."""
    rows = ["  ".join(filter(None, (label, wavelength, medium)))
            for _, label, wavelength, medium in DIAGNOSTIC_LINES]
    Path(path).write_text("\n".join(rows) + "\n")


def input_commands(params: CloudyParameters):
    """Return the C25 command stream for one model."""
    params.validate()
    commands = [
        ("title LRD Cloudy grid "
         f"logn={params.logn:g} logU={params.logu:g} logNH={params.lognh:g}"),
        SED_COMMANDS[params.sed],
        f"hden {params.logn:g}",
        f"ionization parameter {params.logu:g}",
        "abundances GASS",
    ]
    if params.dust_to_metals > 0:
        commands.extend([
            f"grains ism {params.dust_to_metals:g} no qheat",
            f"metals and grains {params.metallicity:g} linear",
        ])
    else:
        commands.append(f"metals {params.metallicity:g} linear")
    if params.microturbulence_kms > 0:
        commands.append(
            f"turbulence {params.microturbulence_kms:g} km/sec no pressure"
        )
    if params.no_molecules:
        commands.append("no molecules")
    if params.geometry == "sphere":
        commands.extend([f"radius {params.radius_log_cm:g}", "sphere static"])
    commands.append(f"stop column density {params.lognh:g}")
    if params.temperature is not None:
        commands.append(f"constant temperature {params.temperature:g} K")
    commands.extend([
        ("iterate to convergence" if params.iterations is None
         else f"iterate {params.iterations}"),
        'save overview "overview.out" last',
        ('save linelist "integrated_lines.out" "lrd_lines.dat" '
         'last no hash emergent absolute'),
        'save lines emissivity "emissivity.out" last',
    ])
    commands.extend(f"{label}  {wavelength}" for _, label, wavelength, _ in DIAGNOSTIC_LINES)
    commands.append("end lines")
    return commands


def write_input(path, logn=None, logu=None, lognh=None, temperature=None,
                params: CloudyParameters | None = None, **kwargs):
    """Write a C25 deck; the legacy scalar call remains supported."""
    if params is None:
        if logn is None or logu is None or lognh is None:
            raise TypeError("provide params or logn, logu, and lognh")
        params = CloudyParameters(
            logn=logn, logu=logu, lognh=lognh, temperature=temperature, **kwargs
        )
    Path(path).write_text("\n".join(input_commands(params)) + "\n")
    return params


def resolve_executable(executable=None):
    """Resolve an explicit executable, the environment, or the local build."""
    candidate = executable or os.environ.get("CLOUDY_EXE") or DEFAULT_CLOUDY_EXE
    exe = Path(candidate).expanduser().resolve()
    if not exe.is_file() or not os.access(exe, os.X_OK):
        raise RuntimeError(
            "Cloudy unavailable: build the local source or set CLOUDY_EXE to "
            "a verified executable with its atomic data"
        )
    return exe


def run_cloudy(workdir, executable=None, timeout=900):
    """Run ``model.in`` in *workdir*, failing on errors and timeouts."""
    exe = resolve_executable(executable)
    env = os.environ.copy()
    env.update({"LC_ALL": "C", "LANG": "C"})
    return subprocess.run(
        [str(exe), "-r", "model"],
        cwd=workdir,
        check=True,
        capture_output=True,
        text=True,
        timeout=timeout,
        env=env,
    )


def parse_integrated_lines(path):
    """Parse the last row of a Cloudy ``save linelist ... absolute`` file."""
    rows = [line.rstrip("\n") for line in Path(path).read_text().splitlines()
            if line.strip()]
    header = next((row for row in rows if row.startswith("#lineslist")), None)
    data = next((row for row in reversed(rows) if row.startswith("iteration ")), None)
    if header is None or data is None:
        raise ValueError(f"incomplete Cloudy line list: {path}")
    values = data.split("\t")[1:]
    if len(values) != len(DIAGNOSTIC_LINES):
        raise ValueError(
            f"expected {len(DIAGNOSTIC_LINES)} lines, found {len(values)}"
        )
    return {key: float(value) for (key, *_), value in zip(DIAGNOSTIC_LINES, values)}


def parse_run_status(path):
    """Extract machine-checkable completion information from ``model.out``."""
    text = Path(path).read_text(errors="replace")
    match = re.search(
        r"Cloudy ends: (\d+) zones, (\d+) iterations(?:, (\d+) cautions)?", text
    )
    if match is None or "Cloudy exited OK" not in text:
        raise ValueError("Cloudy output does not contain a successful completion marker")
    return {
        "zones": int(match.group(1)),
        "iterations": int(match.group(2)),
        "cautions": int(match.group(3) or 0),
        "cloudy_exited_ok": True,
    }


def photon_normalized_yields(lines, params: CloudyParameters):
    """Convert absolute line output to emitted erg per incident H photon."""
    # Specifying a radius and spherical geometry does not by itself switch
    # Cloudy's line printout to the luminosity case; with U as the continuum
    # normalization, ``save linelist absolute`` remains a surface flux.
    return {key: value / params.photon_flux for key, value in lines.items()}


def run_model(workdir, params: CloudyParameters, executable=None, timeout=900):
    """Generate, run, and parse one self-contained Cloudy model."""
    directory = Path(workdir)
    directory.mkdir(parents=True, exist_ok=True)
    write_line_list(directory / "lrd_lines.dat")
    write_input(directory / "model.in", params=params)
    completed = run_cloudy(directory, executable=executable, timeout=timeout)
    lines = parse_integrated_lines(directory / "integrated_lines.out")
    status = parse_run_status(directory / "model.out")
    return {
        "parameters": asdict(params),
        "status": status,
        "absolute_lines": lines,
        "erg_per_ionizing_photon": photon_normalized_yields(lines, params),
        "returncode": completed.returncode,
    }
